#!/bin/bash
sudo apt-get install build-essential
sudo apt-get install curl
sudo apt-get install apt-transport-https
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

# Mngo




