---
- name: Installing dependencies
  become: yes
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - build-essential
    - git
    - curl

- name: making sure that the system can use the HTTPS
  stat: path=/usr/lib/apt/methods/https
  register: apt_https_transport

- name: Installing HTTPS transport for APT
  become: yes
  apt: pkg=apt-transport-https state=installed
  when: not apt_https_transport.stat.exists

- name: Importing the NodeSource GPG key into apt
  become: yes
  apt_key: >
    id=68576280 
    url="https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
    validate_certs=False

- name: Adding NodeSource deb repository
  become: yes
  apt_repository: repo='deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main' state=present

- name: Installing Node.js
  become: yes
  apt: pkg=nodejs state=installed update_cache=yes