---
- name: Install required system packages.
  apt: pkg={{ item }} state=present update-cache=yes
  with_items:
    - libmysqlclient-dev
    - python-dev
    - python-pip
    - gcc
    - python-setuptools
    - mysql-server
    - git-core
    - mysql-client
    - python-setuptools
  become: yes

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: Install the Python MySQLB module
  pip: name=MySQL-python
  become: yes

- debug: 
    msg: "{{ ansible_env.HOME}}"

- name: update mysql root password for all root accounts
  mysql_user: name=root
                host=localhost
                password="{{ root_db_password }}"
                check_implicit_admin=yes
                state=present

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: copy .my.cnf file with root password credentials
  # template: src=templates/.my.cnf dest=/home/vagrant/.my.cnf owner=root mode=0644
  template: src=templates/my.cnf dest=/etc/mysql/my.cnf owner=vagrant mode=0644

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ root_db_password }}
  with_items:
    - localhost
    # IPV6 localhost
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - ::1
    - "{{ inventory_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Restarting mysql service
  service: name=mysql state=restarted
