---
- name: Copying static analysis script to jenkins server
  copy: 
    src: files/{{item}}
    dest: "{{jenkins_path}}/{{item}}"
  with_items:
    - package.json
    - analysis.js

#- name: Cloning Useless Test Detector
#  git:
#    repo: "https://github.ncsu.edu/rmehta4/TestModule.git"
#    dest: "{{jenkins_path}}/BuildTool"

- name: Compile Useless Test Detector
  args:
    chdir: "{{jenkins_path}}/BuildTools/UselessTest"
  shell: mvn compile
