---
- name: Adding mongodb key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927

- name: Adding mongodb repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse
    state: present

- name: Installing mongodb using apt-get
  shell: yes | sudo apt-get install mongodb
  become: true

- name: Installing Python-Pip
  apt:
    pkg: python-pip
    state: latest

- name: Installing the latest pymongo package
  pip: name=pymongo state=latest use_mirrors=no

